import { automateCityBuild } from "../pageAutomation/build";
import { automateResearch } from "../pageAutomation/research";


export const queueEarlyGameStandard = {
    index: 0,
    lastIndex: null,
    completed: null,
    queueFunctions : [
        automateResearch("housing"),
        automateCityBuild("common_house", 3),
        automateResearch("agriculture"),
        automateCityBuild("farm", 1),
        automateCityBuild("common_house", 4),
        automateCityBuild("farm", 2),
        automateResearch("wood_cutting"),
        automateCityBuild("common_house", 5),
        automateCityBuild("lumberjack_camp", 1),
        automateCityBuild("common_house", 6),
        automateCityBuild("lumberjack_camp", 2),
        automateCityBuild("common_house", 7),
        automateCityBuild("farm", 3),
        automateCityBuild("lumberjack_camp", 3),
        automateResearch("stone_masonry"),
        automateCityBuild("common_house", 8),
        automateCityBuild("quarry", 2),
        automateCityBuild("common_house", 9),
        automateResearch("pottery"),
        automateCityBuild("farm", 4),
        automateCityBuild("lumberjack_camp", 4),
        automateCityBuild("common_house", 10),
        automateResearch("storage"),
        automateCityBuild("artisan_workshop", 1),
        automateCityBuild("farm", 5),
        automateResearch("crop_rotation"),
        automateCityBuild("lumberjack_camp", 5),
        automateResearch("woodcarvers"),
        automateCityBuild("farm", 7),
        automateCityBuild("common_house", 11),
        automateCityBuild("artisan_workshop", 2),
        automateCityBuild("common_house", 12),
        automateCityBuild("quarry", 5),
        automateResearch("stone_extraction_tools"),
        automateCityBuild("lumberjack_camp", 7),
        automateCityBuild("common_house", 13),
        automateCityBuild("artisan_workshop", 3),
        automateCityBuild("store", 1),
        automateCityBuild("common_house", 14),  
        automateCityBuild("artisan_workshop", 4),
        automateCityBuild("common_house", 15),
        automateCityBuild("artisan_workshop", 5),
        automateResearch("local_products"),
        automateCityBuild("school", 2),
        
    ]
}